### ISSUE TITLE
Fix all the issues found by the linter

### ISSUE THREAD

**Issue by ceilican** [StabilityNexus/Clowder#6]
See the issues found by linter here: https://github.com/StabilityNexus/Clowder/actions/runs/12111579470/job/33763655833

Fix them all until the linter passes successfully.

**Comment by ceilican** [comment]
Assigned!

**Comment by Arnav-Nehra** [comment]
@blizet,

Have you started working on the task? I actually completed it already but forgot to ask for assigning. However, if you have already begun, please feel free to continue."

**Comment by blizet** [comment]
If you have already done it feel free to raise a PR

**Comment by Arnav-Nehra** [comment]
well it's assigned to you, go with it,  i'll work on another one.
